import type { Camera, Film, SearchEntity, Technique } from "@/types";

const commonsFile = (name: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(name)}?width=1400`;

export const films: Film[] = [
  {
    kind: "film",
    slug: "kodak-portra-400",
    name: "Kodak Portra 400",
    brand: "Kodak",
    iso: 400,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120", "Sheet Film"],
    description: "A daylight-balanced color negative film widely used for portraits and mixed lighting thanks to broad exposure latitude and restrained contrast.",
    characteristics: { Grain: "Fine", Contrast: "Low", Saturation: "Medium", "Exposure latitude": "Very High" },
    uses: ["Portrait", "Travel", "Street"],
    image: {
      url: commonsFile("Kodak Portra 400 120 film.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kodak_Portra_400_120_film.jpg",
      creator: "RostislavNickel",
      license: "CC BY-SA (see source page)",
      attributionRequired: true,
      alt: "Kodak Portra 400 120 roll film",
    },
  },
  {
    kind: "film",
    slug: "kodak-gold-200",
    name: "Kodak Gold 200",
    brand: "Kodak",
    iso: 200,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120"],
    description: "A consumer color negative film with a warm, saturated rendering suited to daylight, travel, and everyday photography.",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "High", "Exposure latitude": "Medium" },
    uses: ["Travel", "Everyday", "Landscape"],
    image: {
      url: commonsFile("Kodak-gold-200.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kodak-gold-200.jpg",
      creator: "Runningboards",
      license: "CC0 1.0",
      attributionRequired: false,
      alt: "Kodak Gold 200 35mm film cartridge",
    },
  },
  {
    kind: "film",
    slug: "ilford-hp5-plus",
    name: "Ilford HP5 Plus",
    brand: "Ilford",
    iso: 400,
    filmType: "Black & White",
    process: "B&W",
    formats: ["35mm", "120", "Sheet Film"],
    description: "A versatile high-speed black-and-white film known for flexible exposure and a classic, visible grain structure.",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "N/A", "Exposure latitude": "High" },
    uses: ["Street", "Documentary", "Low Light"],
    image: {
      url: commonsFile("Ilford HP5 Plus - Black & white film with original box.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ilford_HP5_Plus_-_Black_%26_white_film_with_original_box.jpg",
      creator: "Dnalor 01",
      license: "CC BY-SA 3.0 AT",
      attributionRequired: true,
      alt: "Ilford HP5 Plus 35mm film with original box",
    },
  },
  {
    kind: "film",
    slug: "cinestill-800t",
    name: "CineStill 800T",
    brand: "CineStill",
    iso: 800,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120"],
    description: "A tungsten-balanced high-speed color film commonly chosen for artificial light and night photography.",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "Medium", "Exposure latitude": "High" },
    uses: ["Night", "Urban", "Artificial Light"],
    image: {
      url: commonsFile("Cinestill 800Tungsten Xpro C-41 135 film cartridge (03).jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Cinestill_800Tungsten_Xpro_C-41_135_film_cartridge_(03).jpg",
      creator: "El Grafo",
      license: "CC BY-SA 4.0",
      attributionRequired: true,
      alt: "CineStill 800T 35mm film cartridge",
    },
  },
];

export const cameras: Camera[] = [
  {
    kind: "camera",
    slug: "canon-ae-1",
    name: "Canon AE-1",
    brand: "Canon",
    releaseYear: 1976,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Canon FD",
    shutter: "Electronically controlled focal-plane shutter",
    shutterSpeed: "2s–1/1000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual", "Shutter Priority"],
    battery: "4LR44 / PX28-type 6V",
    weight: "590 g (body)",
    flashSync: "1/60s",
    description: "A landmark electronic 35mm SLR from Canon's A-series, designed around manual focus FD lenses and shutter-priority automation.",
    image: {
      url: commonsFile("CanonAE1.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:CanonAE1.jpg",
      creator: "SixxiA / Tom Mead",
      license: "Public Domain",
      attributionRequired: false,
      alt: "Canon AE-1 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "nikon-fm2",
    name: "Nikon FM2",
    brand: "Nikon",
    releaseYear: 1982,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Nikon F",
    shutter: "Vertical-travel mechanical focal-plane shutter",
    shutterSpeed: "1s–1/4000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual"],
    battery: "2× LR44/SR44 for meter",
    weight: "540 g (body)",
    flashSync: "1/200s (early FM2; later variants differ)",
    description: "A compact mechanical Nikon SLR known for a wide shutter-speed range and operation without battery power apart from the meter.",
    image: {
      url: commonsFile("Nikon FM2 camera.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Nikon_FM2_camera.jpg",
      creator: "Gaurav Dhwaj Khadka",
      license: "CC BY-SA 4.0",
      attributionRequired: true,
      alt: "Nikon FM2 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "pentax-k1000",
    name: "Pentax K1000",
    brand: "Pentax",
    releaseYear: 1976,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Pentax K",
    shutter: "Mechanical focal-plane shutter",
    shutterSpeed: "1s–1/1000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual"],
    battery: "LR44/SR44-type for meter",
    weight: "Varies by production version",
    flashSync: "1/60s",
    description: "A deliberately simple manual-focus SLR whose straightforward controls made it common in photography education.",
    image: {
      url: commonsFile("Pentax K1000.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Pentax_K1000.jpg",
      creator: "Martin Taylor",
      license: "CC BY-SA 2.5",
      attributionRequired: true,
      alt: "Pentax K1000 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "olympus-om-1",
    name: "Olympus OM-1",
    brand: "Olympus",
    releaseYear: 1972,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Olympus OM",
    shutter: "Mechanical focal-plane shutter",
    shutterSpeed: "1s–1/1000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual"],
    battery: "Meter battery only; original mercury cell specification",
    weight: "Approx. 510 g (body)",
    flashSync: "1/60s",
    description: "A compact professional-era SLR that helped establish the small-body OM System design language.",
    image: {
      url: commonsFile("Olympus OM1.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Olympus_OM1.jpg",
      creator: "Alberto.bidinot",
      license: "Public Domain",
      attributionRequired: false,
      alt: "Olympus OM-1 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "leica-m6",
    name: "Leica M6",
    brand: "Leica",
    releaseYear: 1984,
    cameraType: "Rangefinder",
    filmFormat: "35mm",
    lensMount: "Leica M",
    shutter: "Mechanical cloth focal-plane shutter",
    shutterSpeed: "1s–1/1000s + B",
    metering: "TTL selective meter",
    exposureModes: ["Manual"],
    battery: "Meter battery only",
    weight: "Approx. 560 g (classic body)",
    flashSync: "1/50s",
    description: "A mechanical Leica M rangefinder with built-in TTL metering, produced in its classic form from the 1980s into the 1990s.",
    image: {
      url: commonsFile("Leica M6.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Leica_M6.jpg",
      creator: "Noqqe",
      license: "CC0 1.0",
      attributionRequired: false,
      alt: "Leica M6 rangefinder camera",
    },
  },
];

export const techniques: Technique[] = [
  {
    kind: "technique",
    slug: "sunny-16-rule",
    name: "Sunny 16 Rule",
    category: "Exposure",
    difficulty: "Beginner",
    minutes: 4,
    summary: "Estimate daylight exposure without a meter by pairing f/16 with a shutter speed near the reciprocal of film ISO.",
    sections: [
      { heading: "Starting point", body: "In bright sun, start around f/16 and choose a shutter speed close to 1/ISO. ISO 100 maps roughly to 1/125s; ISO 400 maps roughly to 1/500s." },
      { heading: "Treat it as an estimate", body: "Cloud cover, subject reflectance, latitude, and creative intent can all justify a different exposure. Use the rule as a baseline, not a replacement for metering when precision matters." },
    ],
  },
  {
    kind: "technique",
    slug: "push-processing",
    name: "Push Processing",
    category: "Film Processing",
    difficulty: "Intermediate",
    minutes: 6,
    summary: "Expose film at a higher effective speed and compensate during development, usually trading shadow detail for more contrast and visible grain.",
    sections: [
      { heading: "Exposure", body: "A one-stop push commonly means rating ISO 400 film at EI 800. The development adjustment depends on film, developer, chemistry, temperature, and laboratory procedure." },
      { heading: "Development", body: "There is no universal percentage or processing time. Follow the film/developer datasheet or the lab's published push-processing guidance." },
    ],
  },
  {
    kind: "technique",
    slug: "loading-35mm-film",
    name: "Loading 35mm Film",
    category: "Getting Started",
    difficulty: "Beginner",
    minutes: 5,
    summary: "Load a 35mm cartridge, engage the leader with the take-up mechanism, and verify transport before closing the camera back.",
    sections: [
      { heading: "Load", body: "Place the cartridge in its chamber, pull the leader across, and secure it according to the camera's take-up spool or auto-load design." },
      { heading: "Verify", body: "Advance the film and check that the rewind crank or transport indicator moves as expected. Camera-specific manuals take priority over generic instructions." },
    ],
    image: {
      url: commonsFile("Illford HP5+ loading.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Illford_HP5%2B_loading.jpg",
      creator: "Wikimedia Commons contributor (see source page)",
      license: "See source page",
      attributionRequired: true,
      alt: "Loading Ilford HP5 Plus film into a 35mm camera",
    },
  },
  {
    kind: "technique",
    slug: "long-exposure",
    name: "Long Exposure",
    category: "Creative Techniques",
    difficulty: "Intermediate",
    minutes: 7,
    summary: "Use slow shutter speeds to record motion or low light while accounting for stability, metering, and reciprocity behavior.",
    sections: [
      { heading: "Stability", body: "A tripod and cable release reduce camera movement. Bulb mode is useful when the required exposure exceeds the camera's timed shutter range." },
      { heading: "Reciprocity", body: "Many films deviate from linear response at long exposure times. Check the manufacturer's reciprocity guidance for the specific emulsion whenever available." },
    ],
    image: {
      url: commonsFile("Long Exposure at Night of a Road on Cinestill 800T.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Long_Exposure_at_Night_of_a_Road_on_Cinestill_800T.jpg",
      creator: "Arandomphotographer",
      license: "See source page",
      attributionRequired: true,
      alt: "Long exposure night photograph made on CineStill 800T",
    },
  },
];

export const allEntities: SearchEntity[] = [...films, ...cameras, ...techniques];

export function findBySlug<T extends { slug: string }>(items: T[], slug: string) {
  return items.find((item) => item.slug === slug);
}
