import type { Camera, Film, SearchEntity, Technique } from "@/types";

const commonsFile = (name: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(name)}?width=1400`;

export const films: Film[] = [
  {
    kind: "film",
    slug: "kodak-portra-400",
    name: "Kodak Portra 400",
    brand: "Kodak",
    iso: 400,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120", "Sheet Film"],
    description: "A daylight-balanced color negative film widely used for portraits and mixed lighting thanks to broad exposure latitude and restrained contrast.",
    descriptionTh: "ฟิล์มเนกาทีฟสีสมดุลแสงกลางวันยอดนิยมสำหรับงานพอร์ตเทรตและสภาพแสงหลากหลาย จุดเด่นคือช่วงเผื่อการรับแสงกว้างและคอนทราสต์ค่อนข้างนุ่ม",
    characteristics: { Grain: "Fine", Contrast: "Low", Saturation: "Medium", "Exposure latitude": "Very High" },
    uses: ["Portrait", "Travel", "Street"],
    image: {
      url: commonsFile("Kodak Portra 400 120 film.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kodak_Portra_400_120_film.jpg",
      creator: "RostislavNickel",
      license: "CC BY-SA (see source page)",
      attributionRequired: true,
      alt: "Kodak Portra 400 120 roll film",
    },
  },
  {
    kind: "film",
    slug: "kodak-portra-160",
    name: "Kodak Portra 160",
    brand: "Kodak",
    iso: 160,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120", "Sheet Film"],
    description: "A lower-speed Portra stock designed around fine grain, restrained contrast, and natural color rendering for controlled light and portrait work.",
    descriptionTh: "Portra ความไวแสงต่ำที่เน้นเกรนละเอียด คอนทราสต์นุ่ม และการถ่ายทอดสีเป็นธรรมชาติ เหมาะกับพอร์ตเทรตและงานที่ควบคุมแสงได้",
    characteristics: { Grain: "Fine", Contrast: "Low", Saturation: "Medium", "Exposure latitude": "High" },
    uses: ["Portrait", "Fashion", "Travel"],
    image: {
      url: commonsFile("Kodak Portra 160 135 film cartridge (02).jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kodak_Portra_160_135_film_cartridge_(02).jpg",
      creator: "El Grafo",
      license: "See source page",
      attributionRequired: true,
      alt: "Kodak Portra 160 35mm film cartridge",
    },
  },
  {
    kind: "film",
    slug: "kodak-portra-800",
    name: "Kodak Portra 800",
    brand: "Kodak",
    iso: 800,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120"],
    description: "The highest-speed Portra film, intended for lower-light situations while retaining the family’s portrait-oriented color rendering.",
    descriptionTh: "Portra ที่มีความไวแสงสูงที่สุดในตระกูล เหมาะกับสภาพแสงน้อยโดยยังคงบุคลิกสีที่เน้นงานบุคคลของ Portra",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "Medium", "Exposure latitude": "High" },
    uses: ["Portrait", "Low Light", "Night"],
    image: {
      url: commonsFile("Kodak Portra 800 135 film cartridge 01.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kodak_Portra_800_135_film_cartridge_01.jpg",
      creator: "El Grafo",
      license: "CC BY-SA 4.0",
      attributionRequired: true,
      alt: "Kodak Portra 800 35mm film cartridge",
    },
  },
  {
    kind: "film",
    slug: "kodak-gold-200",
    name: "Kodak Gold 200",
    brand: "Kodak",
    iso: 200,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120"],
    description: "A consumer color negative film with a warm, saturated rendering suited to daylight, travel, and everyday photography.",
    descriptionTh: "ฟิล์มเนกาทีฟสีสำหรับการใช้งานทั่วไป ให้ภาพโทนอุ่นและสีค่อนข้างอิ่ม เหมาะกับกลางวัน การเดินทาง และภาพในชีวิตประจำวัน",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "High", "Exposure latitude": "Medium" },
    uses: ["Travel", "Everyday", "Landscape"],
    image: {
      url: commonsFile("Kodak-gold-200.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kodak-gold-200.jpg",
      creator: "Runningboards",
      license: "CC0 1.0",
      attributionRequired: false,
      alt: "Kodak Gold 200 35mm film cartridge",
    },
  },
  {
    kind: "film",
    slug: "kodak-ektar-100",
    name: "Kodak Ektar 100",
    brand: "Kodak",
    iso: 100,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120", "Sheet Film"],
    description: "A fine-grain ISO 100 color negative film with vivid saturation and high sharpness, commonly selected for landscapes, travel, and product work.",
    descriptionTh: "ฟิล์มเนกาทีฟสี ISO 100 เกรนละเอียด สีสดและความคมชัดสูง นิยมใช้กับภาพภูมิทัศน์ การเดินทาง และงานสินค้า",
    characteristics: { Grain: "Fine", Contrast: "Medium", Saturation: "High", Sharpness: "High", "Exposure latitude": "Medium" },
    uses: ["Landscape", "Travel", "Product", "Nature"],
    image: {
      url: commonsFile("Ektar 100.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ektar_100.jpg",
      creator: "Will Folsom",
      license: "CC BY 2.0",
      attributionRequired: true,
      alt: "Kodak Ektar 100 film",
    },
  },
  {
    kind: "film",
    slug: "kodak-colorplus-200",
    name: "Kodak ColorPlus 200",
    brand: "Kodak",
    iso: 200,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm"],
    description: "An ISO 200 consumer color negative film intended for everyday daylight photography with a familiar warm color palette.",
    descriptionTh: "ฟิล์มเนกาทีฟสี ISO 200 สำหรับการถ่ายทั่วไปในแสงกลางวัน มีบุคลิกสีโทนอุ่นแบบฟิล์มผู้บริโภคของ Kodak",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "High", "Exposure latitude": "Medium" },
    uses: ["Everyday", "Travel", "Street"],
    image: {
      url: commonsFile("Kodak ColorPlus 200 135 film cartridge and box.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kodak_ColorPlus_200_135_film_cartridge_and_box.jpg",
      creator: "El Grafo",
      license: "See source page",
      attributionRequired: true,
      alt: "Kodak ColorPlus 200 35mm cartridge and box",
    },
  },
  {
    kind: "film",
    slug: "kodak-ultramax-400",
    name: "Kodak Ultramax 400",
    brand: "Kodak",
    iso: 400,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm"],
    description: "A general-purpose ISO 400 consumer color film that trades some grain for greater flexibility across daylight, overcast, and casual indoor scenes.",
    descriptionTh: "ฟิล์มสี ISO 400 สำหรับใช้งานทั่วไป มีความยืดหยุ่นกว่า ISO ต่ำในวันที่ครึ้มและการถ่ายภายในอาคาร โดยแลกกับเกรนที่เห็นได้มากขึ้น",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "High", "Exposure latitude": "Medium" },
    uses: ["Everyday", "Travel", "Street", "Low Light"],
    image: {
      url: commonsFile("Kodak Ultramax 400 135 film cartridge and box (02).jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kodak_Ultramax_400_135_film_cartridge_and_box_(02).jpg",
      creator: "El Grafo",
      license: "See source page",
      attributionRequired: true,
      alt: "Kodak Ultramax 400 35mm cartridge and box",
    },
  },
  {
    kind: "film",
    slug: "ilford-hp5-plus",
    name: "Ilford HP5 Plus",
    brand: "Ilford",
    iso: 400,
    filmType: "Black & White",
    process: "B&W",
    formats: ["35mm", "120", "Sheet Film"],
    description: "A versatile high-speed black-and-white film known for flexible exposure and a classic, visible grain structure.",
    descriptionTh: "ฟิล์มขาวดำความไวสูงที่ใช้งานได้หลากหลาย มีช่วงการรับแสงยืดหยุ่นและเกรนแบบคลาสสิกที่มองเห็นได้ชัด",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "N/A", "Exposure latitude": "High" },
    uses: ["Street", "Documentary", "Low Light"],
    image: {
      url: commonsFile("Ilford HP5 Plus - Black & white film with original box.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ilford_HP5_Plus_-_Black_%26_white_film_with_original_box.jpg",
      creator: "Dnalor 01",
      license: "CC BY-SA 3.0 AT",
      attributionRequired: true,
      alt: "Ilford HP5 Plus 35mm film with original box",
    },
  },
  {
    kind: "film",
    slug: "ilford-fp4-plus",
    name: "Ilford FP4 Plus",
    brand: "Ilford",
    iso: 125,
    filmType: "Black & White",
    process: "B&W",
    formats: ["35mm", "120", "Sheet Film"],
    description: "A medium-speed black-and-white film with fine grain and broad application across outdoor, studio, technical, and enlargement-focused work.",
    descriptionTh: "ฟิล์มขาวดำความไวปานกลางที่เน้นเกรนละเอียด เหมาะทั้งงานกลางแจ้ง สตูดิโอ งานเทคนิค และงานที่ต้องการขยายภาพขนาดใหญ่",
    characteristics: { Grain: "Fine", Contrast: "Medium", Saturation: "N/A", "Exposure latitude": "High" },
    uses: ["Portrait", "Landscape", "Documentary"],
    image: {
      url: commonsFile("Ilford FP4 Plus - Black & white film with original box.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ilford_FP4_Plus_-_Black_%26_white_film_with_original_box.jpg",
      creator: "Dnalor 01",
      license: "See source page",
      attributionRequired: true,
      alt: "Ilford FP4 Plus film with original box",
    },
  },
  {
    kind: "film",
    slug: "ilford-delta-400",
    name: "Ilford Delta 400 Professional",
    brand: "Ilford",
    iso: 400,
    filmType: "Black & White",
    process: "B&W",
    formats: ["35mm", "120"],
    description: "A modern ISO 400 black-and-white film designed for a relatively fine grain structure and detailed rendering at a useful general-purpose speed.",
    descriptionTh: "ฟิล์มขาวดำ ISO 400 แบบสมัยใหม่ที่ออกแบบให้ได้เกรนค่อนข้างละเอียดและรายละเอียดสูง ในความไวที่เหมาะกับการใช้งานทั่วไป",
    characteristics: { Grain: "Fine", Contrast: "Medium", Saturation: "N/A", "Exposure latitude": "High" },
    uses: ["Street", "Portrait", "Low Light"],
    image: {
      url: commonsFile("Ilford Delta 400 - Black & white film.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ilford_Delta_400_-_Black_%26_white_film.jpg",
      creator: "Dnalor 01",
      license: "See source page",
      attributionRequired: true,
      alt: "Ilford Delta 400 Professional black and white film",
    },
  },
  {
    kind: "film",
    slug: "cinestill-800t",
    name: "CineStill 800T",
    brand: "CineStill",
    iso: 800,
    filmType: "Color Negative",
    process: "C-41",
    formats: ["35mm", "120"],
    description: "A tungsten-balanced high-speed color film commonly chosen for artificial light and night photography.",
    descriptionTh: "ฟิล์มสีความไวสูงสมดุลแสงทังสเตน นิยมใช้กับแสงประดิษฐ์และการถ่ายภาพกลางคืน",
    characteristics: { Grain: "Medium", Contrast: "Medium", Saturation: "Medium", "Exposure latitude": "High" },
    uses: ["Night", "Urban", "Artificial Light"],
    image: {
      url: commonsFile("Cinestill 800Tungsten Xpro C-41 135 film cartridge (03).jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Cinestill_800Tungsten_Xpro_C-41_135_film_cartridge_(03).jpg",
      creator: "El Grafo",
      license: "CC BY-SA 4.0",
      attributionRequired: true,
      alt: "CineStill 800T 35mm film cartridge",
    },
  },
];

export const cameras: Camera[] = [
  {
    kind: "camera",
    slug: "canon-ae-1",
    name: "Canon AE-1",
    brand: "Canon",
    releaseYear: 1976,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Canon FD",
    shutter: "Electronically controlled focal-plane shutter",
    shutterSpeed: "2s–1/1000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual", "Shutter Priority"],
    battery: "4LR44 / PX28-type 6V",
    weight: "590 g (body)",
    flashSync: "1/60s",
    description: "A landmark electronic 35mm SLR from Canon's A-series, designed around manual focus FD lenses and shutter-priority automation.",
    descriptionTh: "SLR 35 มม. ระบบอิเล็กทรอนิกส์รุ่นสำคัญของ Canon A-series ใช้เลนส์โฟกัสมือเมาท์ FD และมีโหมดอัตโนมัติแบบกำหนดความเร็วชัตเตอร์",
    image: {
      url: commonsFile("CanonAE1.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:CanonAE1.jpg",
      creator: "SixxiA / Tom Mead",
      license: "Public Domain",
      attributionRequired: false,
      alt: "Canon AE-1 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "canon-a-1",
    name: "Canon A-1",
    brand: "Canon",
    releaseYear: 1978,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Canon FD",
    shutter: "Electronically controlled cloth focal-plane shutter",
    shutterSpeed: "30s–1/1000s + B",
    metering: "TTL center-weighted averaging",
    exposureModes: ["Manual", "Aperture Priority", "Shutter Priority", "Program"],
    battery: "4LR44 / PX28-type 6V",
    weight: "Approx. 620 g (body)",
    flashSync: "1/60s",
    description: "An advanced A-series SLR combining manual exposure with aperture-priority, shutter-priority, and programmed auto exposure in one body.",
    descriptionTh: "SLR ระดับสูงในตระกูล A-series ที่รวม Manual, Aperture Priority, Shutter Priority และ Program AE ไว้ในบอดี้เดียว",
    image: {
      url: commonsFile("Canon A-1 a.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Canon_A-1_a.jpg",
      creator: "Céréales Killer",
      license: "CC BY-SA 4.0",
      attributionRequired: true,
      alt: "Canon A-1 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "nikon-fm2",
    name: "Nikon FM2",
    brand: "Nikon",
    releaseYear: 1982,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Nikon F",
    shutter: "Vertical-travel mechanical focal-plane shutter",
    shutterSpeed: "1s–1/4000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual"],
    battery: "2× LR44/SR44 for meter",
    weight: "540 g (body)",
    flashSync: "1/250s on later FM2 variants",
    description: "A compact mechanical Nikon SLR known for a wide shutter-speed range and operation without battery power apart from the meter.",
    descriptionTh: "SLR กลไกขนาดกะทัดรัดของ Nikon มีช่วงความเร็วชัตเตอร์กว้าง และยังถ่ายได้โดยไม่พึ่งแบตเตอรี่ ยกเว้นระบบวัดแสง",
    image: {
      url: commonsFile("Nikon FM2 camera.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Nikon_FM2_camera.jpg",
      creator: "Gaurav Dhwaj Khadka",
      license: "CC BY-SA 4.0",
      attributionRequired: true,
      alt: "Nikon FM2 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "nikon-f3",
    name: "Nikon F3",
    brand: "Nikon",
    releaseYear: 1980,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Nikon F",
    shutter: "Electronically controlled focal-plane shutter",
    shutterSpeed: "8s–1/2000s + B/T",
    metering: "TTL center-weighted",
    exposureModes: ["Manual", "Aperture Priority"],
    battery: "2× LR44/SR44 or CR1/3N",
    weight: "Approx. 715 g (body)",
    flashSync: "1/80s",
    description: "Nikon's third professional F-series SLR, pairing the modular system concept with electronic shutter control and aperture-priority automation.",
    descriptionTh: "SLR มืออาชีพรุ่นที่สามของ Nikon F-series ยังคงระบบโมดูลาร์ของตระกูล F แต่เพิ่มชัตเตอร์ควบคุมด้วยอิเล็กทรอนิกส์และ Aperture Priority",
    image: {
      url: commonsFile("Nikon F3 135 film SLR camera.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Nikon_F3_135_film_SLR_camera.jpg",
      creator: "Wen-Cheng Liu",
      license: "CC BY-SA 2.0",
      attributionRequired: true,
      alt: "Nikon F3 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "pentax-k1000",
    name: "Pentax K1000",
    brand: "Pentax",
    releaseYear: 1976,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Pentax K",
    shutter: "Mechanical focal-plane shutter",
    shutterSpeed: "1s–1/1000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual"],
    battery: "LR44/SR44-type for meter",
    weight: "Varies by production version",
    flashSync: "1/60s",
    description: "A deliberately simple manual-focus SLR whose straightforward controls made it common in photography education.",
    descriptionTh: "SLR โฟกัสมือที่ออกแบบให้เรียบง่ายเป็นพิเศษ การควบคุมตรงไปตรงมาทำให้ถูกใช้แพร่หลายในงานสอนถ่ายภาพ",
    image: {
      url: commonsFile("Pentax K1000.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Pentax_K1000.jpg",
      creator: "Martin Taylor",
      license: "CC BY-SA 2.5",
      attributionRequired: true,
      alt: "Pentax K1000 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "olympus-om-1",
    name: "Olympus OM-1",
    brand: "Olympus",
    releaseYear: 1972,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Olympus OM",
    shutter: "Mechanical focal-plane shutter",
    shutterSpeed: "1s–1/1000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual"],
    battery: "Meter battery only; original mercury cell specification",
    weight: "Approx. 510 g (body)",
    flashSync: "1/60s",
    description: "A compact professional-era SLR that helped establish the small-body OM System design language.",
    descriptionTh: "SLR ขนาดกะทัดรัดจากยุคมืออาชีพที่ช่วยกำหนดแนวทางการออกแบบบอดี้ขนาดเล็กของระบบ Olympus OM",
    image: {
      url: commonsFile("Olympus OM1.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Olympus_OM1.jpg",
      creator: "Alberto.bidinot",
      license: "Public Domain",
      attributionRequired: false,
      alt: "Olympus OM-1 35mm SLR camera",
    },
  },
  {
    kind: "camera",
    slug: "minolta-x-700",
    name: "Minolta X-700",
    brand: "Minolta",
    releaseYear: 1981,
    cameraType: "SLR",
    filmFormat: "35mm",
    lensMount: "Minolta SR / MD",
    shutter: "Electronically controlled horizontal-travel focal-plane shutter",
    shutterSpeed: "4s–1/1000s + B",
    metering: "TTL center-weighted",
    exposureModes: ["Manual", "Aperture Priority", "Program"],
    battery: "2× LR44/SR44",
    weight: "Approx. 505 g (body)",
    flashSync: "1/60s",
    description: "A late manual-focus Minolta SLR centered on Program AE and aperture-priority automation while retaining full manual exposure control.",
    descriptionTh: "SLR โฟกัสมือยุคปลายของ Minolta เด่นด้วย Program AE และ Aperture Priority พร้อมยังคงการควบคุม Manual เต็มรูปแบบ",
    image: {
      url: commonsFile("Minolta x700 analog camera with 50mm lens.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Minolta_x700_analog_camera_with_50mm_lens.jpg",
      creator: "FlanellKamerasFilm",
      license: "See source page",
      attributionRequired: true,
      alt: "Minolta X-700 35mm SLR with 50mm lens",
    },
  },
  {
    kind: "camera",
    slug: "leica-m6",
    name: "Leica M6",
    brand: "Leica",
    releaseYear: 1984,
    cameraType: "Rangefinder",
    filmFormat: "35mm",
    lensMount: "Leica M",
    shutter: "Mechanical cloth focal-plane shutter",
    shutterSpeed: "1s–1/1000s + B",
    metering: "TTL selective meter",
    exposureModes: ["Manual"],
    battery: "Meter battery only",
    weight: "Approx. 560 g (classic body)",
    flashSync: "1/50s",
    description: "A mechanical Leica M rangefinder with built-in TTL metering, produced in its classic form from the 1980s into the 1990s.",
    descriptionTh: "เรนจ์ไฟน์เดอร์ Leica M แบบกลไกที่เพิ่มระบบวัดแสง TTL ในตัว รุ่นคลาสสิกผลิตต่อเนื่องตั้งแต่ยุค 1980 ถึง 1990",
    image: {
      url: commonsFile("Leica M6.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Leica_M6.jpg",
      creator: "Noqqe",
      license: "CC0 1.0",
      attributionRequired: false,
      alt: "Leica M6 rangefinder camera",
    },
  },
  {
    kind: "camera",
    slug: "hasselblad-500cm",
    name: "Hasselblad 500C/M",
    brand: "Hasselblad",
    releaseYear: 1970,
    cameraType: "Medium Format",
    filmFormat: "120 / 220 · 6×6",
    lensMount: "Hasselblad V System",
    shutter: "Leaf shutter in lens",
    shutterSpeed: "Lens dependent, commonly 1s–1/500s + B",
    metering: "None in standard body",
    exposureModes: ["Manual"],
    battery: "None for standard mechanical body",
    weight: "Varies by finder, back, and lens",
    flashSync: "All shutter speeds with compatible leaf-shutter lens",
    description: "A modular 6×6 medium-format SLR built around interchangeable film backs, finders, and leaf-shutter lenses in the Hasselblad V System.",
    descriptionTh: "SLR มีเดียมฟอร์แมต 6×6 แบบโมดูลาร์ เปลี่ยนแม็กกาซีนฟิล์ม ช่องมองภาพ และเลนส์ leaf shutter ได้ในระบบ Hasselblad V",
    image: {
      url: commonsFile("Hasselblad500Cm.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hasselblad500Cm.jpg",
      creator: "BUTTON74",
      license: "CC BY-SA 4.0",
      attributionRequired: true,
      alt: "Hasselblad 500C/M medium format camera",
    },
  },
  {
    kind: "camera",
    slug: "mamiya-rb67-pro-s",
    name: "Mamiya RB67 Pro-S",
    brand: "Mamiya",
    releaseYear: 1974,
    cameraType: "Medium Format",
    filmFormat: "120 / 220 · 6×7",
    lensMount: "Mamiya RB",
    shutter: "Leaf shutter in lens",
    shutterSpeed: "1s–1/400s + T (lens dependent)",
    metering: "None in standard body",
    exposureModes: ["Manual"],
    battery: "None for standard mechanical body",
    weight: "Varies substantially by lens, finder, and film back",
    flashSync: "All shutter speeds with compatible leaf-shutter lens",
    description: "A fully mechanical modular 6×7 SLR known for its rotating film back, bellows focusing, and studio-oriented interchangeable system.",
    descriptionTh: "SLR มีเดียมฟอร์แมต 6×7 แบบกลไกล้วน มีจุดเด่นคือหลังฟิล์มหมุนได้ ระบบโฟกัสด้วย bellows และโครงสร้างโมดูลาร์สำหรับงานสตูดิโอ",
    image: {
      url: commonsFile("Mamiya RB67.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Mamiya_RB67.jpg",
      creator: "Stefan-Xp",
      license: "CC BY-SA 3.0 / GFDL",
      attributionRequired: true,
      alt: "Mamiya RB67 medium format camera",
    },
  },
];

export const techniques: Technique[] = [
  {
    kind: "technique",
    slug: "sunny-16-rule",
    name: "Sunny 16 Rule",
    nameTh: "กฎ Sunny 16",
    category: "Exposure",
    difficulty: "Beginner",
    minutes: 4,
    summary: "Estimate daylight exposure without a meter by pairing f/16 with a shutter speed near the reciprocal of film ISO.",
    summaryTh: "ประเมินค่าแสงกลางวันโดยไม่ใช้มิเตอร์ ด้วยการตั้ง f/16 และเลือกความเร็วชัตเตอร์ใกล้เคียงส่วนกลับของ ISO ฟิล์ม",
    sections: [
      { heading: "Starting point", body: "In bright sun, start around f/16 and choose a shutter speed close to 1/ISO. ISO 100 maps roughly to 1/125s; ISO 400 maps roughly to 1/500s." },
      { heading: "Treat it as an estimate", body: "Cloud cover, subject reflectance, latitude, and creative intent can all justify a different exposure. Use the rule as a baseline, not a replacement for metering when precision matters." },
    ],
    sectionsTh: [
      { heading: "จุดเริ่มต้น", body: "ในแดดจัดให้เริ่มที่ประมาณ f/16 แล้วเลือกความเร็วชัตเตอร์ใกล้เคียง 1/ISO เช่น ISO 100 ใช้ประมาณ 1/125 วินาที และ ISO 400 ใช้ประมาณ 1/500 วินาที" },
      { heading: "ใช้เป็นค่าประมาณ", body: "เมฆ การสะท้อนแสงของวัตถุ ช่วงเผื่อการรับแสงของฟิล์ม และเจตนาทางภาพอาจทำให้ต้องปรับค่า จึงควรใช้กฎนี้เป็นจุดเริ่มต้น ไม่ใช่ตัวแทนมิเตอร์เมื่อจำเป็นต้องแม่นยำ" },
    ],
  },
  {
    kind: "technique",
    slug: "push-processing",
    name: "Push Processing",
    nameTh: "การ Push ฟิล์ม",
    category: "Film Processing",
    difficulty: "Intermediate",
    minutes: 6,
    summary: "Expose film at a higher effective speed and compensate during development, usually trading shadow detail for more contrast and visible grain.",
    summaryTh: "ถ่ายฟิล์มที่ค่า EI สูงกว่าความไวบนกล่อง แล้วชดเชยในการล้าง ซึ่งมักเพิ่มคอนทราสต์และเกรน แต่ลดรายละเอียดในเงา",
    sections: [
      { heading: "Exposure", body: "A one-stop push commonly means rating ISO 400 film at EI 800. The development adjustment depends on film, developer, chemistry, temperature, and laboratory procedure." },
      { heading: "Development", body: "There is no universal percentage or processing time. Follow the film/developer datasheet or the lab's published push-processing guidance." },
    ],
    sectionsTh: [
      { heading: "การตั้งค่าแสง", body: "การ Push +1 stop โดยทั่วไปหมายถึงนำฟิล์ม ISO 400 ไปถ่ายที่ EI 800 ส่วนการชดเชยตอนล้างขึ้นอยู่กับชนิดฟิล์ม น้ำยา เคมี อุณหภูมิ และวิธีของห้องล้าง" },
      { heading: "การล้าง", body: "ไม่มีเปอร์เซ็นต์หรือเวลาล้างสากล ควรอ้างอิง datasheet ของฟิล์ม/น้ำยา หรือคำแนะนำ Push Processing ของแล็บที่ใช้งานจริง" },
    ],
  },
  {
    kind: "technique",
    slug: "loading-35mm-film",
    name: "Loading 35mm Film",
    nameTh: "การใส่ฟิล์ม 35 มม.",
    category: "Getting Started",
    difficulty: "Beginner",
    minutes: 5,
    summary: "Load a 35mm cartridge, engage the leader with the take-up mechanism, and verify transport before closing the camera back.",
    summaryTh: "ใส่ม้วนฟิล์ม 35 มม. เกี่ยวปลายฟิล์มเข้ากับชุดรับฟิล์ม และตรวจสอบว่าฟิล์มเดินจริงก่อนเริ่มถ่าย",
    sections: [
      { heading: "Load", body: "Place the cartridge in its chamber, pull the leader across, and secure it according to the camera's take-up spool or auto-load design." },
      { heading: "Verify", body: "Advance the film and check that the rewind crank or transport indicator moves as expected. Camera-specific manuals take priority over generic instructions." },
    ],
    sectionsTh: [
      { heading: "ใส่ฟิล์ม", body: "วางตลับฟิล์มในช่อง ดึงปลายฟิล์มไปยังอีกฝั่ง และยึดเข้ากับแกนรับฟิล์มหรือกลไก Auto Load ตามการออกแบบของกล้อง" },
      { heading: "ตรวจสอบ", body: "ลองขึ้นฟิล์มแล้วดูว่าปุ่มกรอฟิล์มหรือตัวบอกการเดินฟิล์มเคลื่อนตามปกติหรือไม่ โดยคู่มือของกล้องแต่ละรุ่นควรมีความสำคัญกว่าคำแนะนำทั่วไป" },
    ],
    image: {
      url: commonsFile("Illford HP5+ loading.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Illford_HP5%2B_loading.jpg",
      creator: "Wikimedia Commons contributor (see source page)",
      license: "See source page",
      attributionRequired: true,
      alt: "Loading Ilford HP5 Plus film into a 35mm camera",
    },
  },
  {
    kind: "technique",
    slug: "long-exposure",
    name: "Long Exposure",
    nameTh: "การถ่าย Long Exposure",
    category: "Creative Techniques",
    difficulty: "Intermediate",
    minutes: 7,
    summary: "Use slow shutter speeds to record motion or low light while accounting for stability, metering, and reciprocity behavior.",
    summaryTh: "ใช้ความเร็วชัตเตอร์ต่ำเพื่อบันทึกการเคลื่อนไหวหรือแสงน้อย โดยต้องคำนึงถึงความนิ่ง การวัดแสง และ reciprocity failure ของฟิล์ม",
    sections: [
      { heading: "Stability", body: "A tripod and cable release reduce camera movement. Bulb mode is useful when the required exposure exceeds the camera's timed shutter range." },
      { heading: "Reciprocity", body: "Many films deviate from linear response at long exposure times. Check the manufacturer's reciprocity guidance for the specific emulsion whenever available." },
    ],
    sectionsTh: [
      { heading: "ความนิ่ง", body: "ขาตั้งกล้องและสายลั่นชัตเตอร์ช่วยลดการสั่น ส่วน Bulb mode มีประโยชน์เมื่อเวลารับแสงยาวกว่าช่วงเวลาชัตเตอร์ที่กล้องตั้งได้" },
      { heading: "Reciprocity", body: "ฟิล์มจำนวนมากตอบสนองต่อแสงไม่เป็นเส้นตรงเมื่อเปิดรับแสงนาน ควรตรวจคำแนะนำเรื่อง reciprocity จากผู้ผลิตของฟิล์มแต่ละชนิดเมื่อมีข้อมูล" },
    ],
    image: {
      url: commonsFile("Long Exposure at Night of a Road on Cinestill 800T.jpg"),
      sourceName: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Long_Exposure_at_Night_of_a_Road_on_Cinestill_800T.jpg",
      creator: "Arandomphotographer",
      license: "See source page",
      attributionRequired: true,
      alt: "Long exposure night photograph made on CineStill 800T",
    },
  },
];

export const allEntities: SearchEntity[] = [...films, ...cameras, ...techniques];

export function findBySlug<T extends { slug: string }>(items: T[], slug: string) {
  return items.find((item) => item.slug === slug);
}
